### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by rastemoh** [mojilla/material-snackbar-supplier#1]
I get the following error when I imported the module:
ERROR in ./node_modules/material-snackbar-supplier/src/supplier.js 52:8
Module parse failed: Unexpected token (52:8)
You may need an appropriate loader to handle this file type.
> 50    render() {
> 51      return (
> 52        <SnackBarContext.Consumer>
> 53      {({message}) => {
> 54         return <Component {...this.props} message={message}/>

I also suggest moving the index.js file to the root of the module

**Comment by themojilla** [comment]
@rastemoh  The problem has been solved. Thanks for reporting!
