### ISSUE TITLE
Huge bundle size of everyone who use this library

### ISSUE THREAD

**Issue by amerllica** [mojilla/material-snackbar-supplier#10]
By destructuring import of the `Close` icon of `Material-UI` in the `supplier.js` file, I faced a huge bundle of my project. something about 5mg 😮 

For a test, I omit all of my libraries and based on [Tree Shaking docs of Webpack](https://webpack.js.org/guides/tree-shaking/) I implement the tools and tricks in my project but bundle has no change until I fount the issue and _1 percent I don't think it is `material-snackbar-supplier` causes to this damn bundle_. 

Based on [this material-ui doc](https://material-ui.com/guides/minimizing-bundle-size) the importing of the `Close` icon should change to:

    import CloseIcon from '@material-ui/icons/Close';

So as fast as I can I send a PR, and please assign the `bug` tag to this issue and review and merge my PR and please as fast as you can release a new version.

Thanks a lot bro.

**Comment by themojilla** [comment]
I'm wondering why you even change that before.
It's my bad, I should have told you before.
In addition, there is a related optimization article in material docs which is well-eplained too
