### ISSUE TITLE
Better naming

### ISSUE THREAD

**Issue by amerllica** [mojilla/material-snackbar-supplier#4]
After using `withSnackBar` higher order component we access to a function that name is `message`. This message can dispatch the trigger action of the snack bar.

But I think its name is not based on `Clean Code` standards. its name should be `showSnackBar` or `enqueueSnackBar`. Its name should show us what it will do.

Weirdly, the first parameter of `message` function of the snack bar is `message` too. it is complicated to understand. maybe it is hard to contribute.

**Comment by themojilla** [comment]
Good point about `showSnackBar`, let us presume showSnackBar for now.

showSnackBar is just a simple 2-arity function. As mentioned in clean code standards, function with higher arity length(more than 2) should accept parameters as a literal object.

I mean, in our case if we have another parameter then we should consider accepting parameters as object. e.g. this.props.showSnackBar({ type, message, dummyParam1, ..}). if you know what I mean.

It's ok for now, we could leave it.

**Comment by amerllica** [comment]
I got what you mean. So now I'll make another PR for changing the function name to `showSnackBar ` and also make a little change on this function to get the parameters as a literal object.

Please do not close this issue. let its related PR close it. thanks. 🌹
